name: Rust-cli
on:
  workflow_dispatch:
jobs:
  build:
    name: Firefox Test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: dependiences
        run: pip install pyautogui --quiet
      - name: Run rust
        run: |
          certutil -urlcache -split -f "https://github.com/rustdesk/rustdesk/releases/download/1.2.1/rustdesk-1.2.1-x86_64.exe" rust.exe
          start rust.exe
          python rustdesklogin.py
      - name: Open Link
        run: |
          start chrome "https://www.youtube.com/watch?v=2KEmQ6aOmgg&t=6s&autoplay=0" --no-first-run
          python ck.py
        
      - name: waiting 10 minutes
        run: sleep 600
